name: test
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      commit-sha:
        required: true
        type: string

jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: echooo
        env:
          SHA: ${{ github.sha }}
        run: |
          echo "SHA IS $SHA, ${{ inputs.commit-sha }}"
