name: test
on:
  push:
    branches:
      - testme-*

jobs:
  call-test2-workflow:
    if: ${{ github.event_name != 'push' || (github.event_name == 'push' && github.event.created == false) }}
    uses: saurbhc/test-plz-ignore/.github/workflows/test2.yml@main
