name: test
on:
  push:
    branches:
      - testme-*

jobs:
  testjob:
    if: github.event.created == false
    runs-on: ubuntu-latest
    steps:
      - name: echo hello hello
        run: echo "hello hello"
